# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Scott O'Connor
url:              http://hyde.getpoole.com
baseurl:          /

paginate: 5


author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
